apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-62vm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0006-tenant/ci10t-786-0006-app/devfile-sample-62vm@sha256:d8a1ccbd368ee5b68d4bcfb1f8b3981e0771b37c457206c7723f5de8a2168885
        name: my-nodejs
        resources: {}
status: {}
